(include "assert.ss")
(define (cuberoot x)
  (define (good-enough? guess)
    (< (abs (- (* guess guess guess) x)) 0.001)
  )
  (define (improve guess)
    (/ (+ (/ x (* guess guess)) (* 2 guess)) 3)
  )
  (define (cuberoot-iter guess)
    (if (good-enough? guess)
      guess
      (cuberoot-iter (improve guess))
    )
  )
  (cuberoot-iter 1.0)
)
(asserteq (cuberoot 8.0) 2.0 1)
(asserteq (cuberoot 27.0) 3.0 1)
